# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2018-03-01 23:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_citydict'),
    ]

    operations = [
        migrations.AddField(
            model_name='citydict',
            name='other',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='courseorg',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='organization.CityDict', verbose_name='\u6240\u5728\u57ce\u5e02'),
        ),
    ]
