# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2018-03-01 23:22
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_auto_20180301_2317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citydict',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='\u6dfb\u52a0\u65f6\u95f4'),
        ),
        migrations.AlterField(
            model_name='citydict',
            name='other',
            field=models.CharField(max_length=10, null=True, verbose_name='\u5176\u4ed6\u5740\u63cf\u8ff0'),
        ),
    ]
