# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2018-03-01 23:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0004_auto_20180301_2322'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='citydict',
            name='other',
        ),
    ]
